### ISSUE TITLE
Integrate our site with our MailChimp Account

### ISSUE THREAD

**Issue by toomuchpete** [AFDC/Platinum#128]
Using the MailChimp API, we want to begin tracking user activity. At a minimum, we'd want the following information pushed to MailChimp for all league registrants:

1. Name
1. Gender
1. Last registration date

Additionally, we'd want to give them an option (off by default) to subscribe to our newsletter along with their registration. Data should still be pushed for users who do not want to subscribe, but they should be added to the list in an unsubscribed state.

**Comment by viduni94** [comment]
Hi,
I would like to work on this issue. Could you let me know to which activities MailChimp is used in the system? Is MailChimp used for regular email sending as well? 

Thank you!

**Comment by toomuchpete** [comment]
Hi @viduni94! I appreciate your interest in helping out!

Right now, MailChimp is only used by our league volunteers to communicate with our membership about league events. We do not use them for regular email sending (like password resets). An example of an email we might send in MailChimp is a newsletter letting our members know that league registration opens in two weeks. 

Unfortunately, our MailChimp list is missing a lot of our members. The first step towards fixing this is making sure that user information is synced to MailChimp when someone registers for a league.

One approach to this problem would be:

1. Add a checkbox to "Sign up for the AFDC Newsletter" to registration (off by default)
2. On registration, make a call to the MailChimp API to update a subscriber. ([Using PUT](https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#edit-put_lists_list_id_members_subscriber_hash))
    - If the person checked the box to subscribe, set `status` to 'subscribed'.
    - If they didn't check the box, don't send `status` and instead set `status_if_new` to 'unsubscribed'

This means that if someone checks the box, they will always be subscribed to the newsletter. If they don't check the box, but are already on our MailChimp list, their status won't change. If they don't check the box but are not in MailChimp, they'll be added to our contacts but won't be sent the newsletter.

I'm happy to help or provide whatever direction you might need to get started! Thanks again for commenting! 😸

**Comment by viduni94** [comment]
Thank you for the information! I'll look into this issue!

**Comment by Anagha22** [comment]
Hey @toomuchpete,
Our team Bundledore would like to kickstart the SoC by taking up this issue :)
