### ISSUE TITLE
Registration available early if link is known

### ISSUE THREAD

**Issue by toomuchpete** [AFDC/Platinum#135]
It seems that players can register early if they know the registration URL. Make sure the registration controller is checking that the league is valid for registration.

**Comment by amrtanair** [comment]
Hey @toomuchpete How would we check if the league is valid for registration ?

**Comment by toomuchpete** [comment]
@amrtanair -- great question! There's a `registering?` method on each league that will return `True` if registration is open, `False` otherwise.
