### ISSUE TITLE
Store Tournament schedules/results documents with leagues

### ISSUE THREAD

**Issue by Afdc-president** [AFDC/Platinum#85]
Feature request

Every league has at least one tournament. If it is too complicated to build tournament schedules into the web It would be nice to have a way to attach or store the google docs created by commissioners. This would be good for communicating to all players, recording results for historical purposes, and copying formats from year to year.

There are other way to accomplish the same goal that would be sufficient - the intended functionality is a way to share and store tournament schedules and results.

**Comment by toomuchpete** [comment]
*Note to contributors:* The deliverable for this ticket is not necessarily working code. Typical product and project management tools would be perfectly acceptable. Working with our board to produce wireframes and a set of related tickets would be an excellent contribution.
